name: ChatControlCore
version: '1.4'
main: org.example.ChatControlCore
commands:
  ccc: {}
permissions:
  chatcontrolcore.command.reload: {}
  chatcontrolcore.command.clear: {}
  chatcontrolcore.command.whitelist: {}
  chatcontrolcore.command.update: {}
  chatcontrolcore.command.mute: {}
  chatcontrolcore.command.private: {}
  chatcontrolcore.command.private.acceptdecline: {}
  chatcontrolcore.command.user: {}
